# Generated by Django 5.1 on 2024-09-26 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_category_inventoryproduct_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryproduct',
            old_name='Date_added',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='inventoryproduct',
            old_name='Last_updated',
            new_name='last_updated',
        ),
        migrations.RenameField(
            model_name='inventoryproduct',
            old_name='Price',
            new_name='price',
        ),
    ]
