# Generated by Django 5.1 on 2024-10-04 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='user',
        ),
        migrations.AlterField(
            model_name='inventorychange',
            name='quantity_change',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
