# Generated by Django 5.1 on 2024-10-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_store_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryproduct',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
