# Generated by Django 5.1.1 on 2024-10-07 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventoryproduct_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryproduct',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.store'),
        ),
    ]
